main: com.simondoestuff.FishOn.Main
name: FishOn
author: simondoestuff
version: 1.0.0
api-version: "1.14"
commands:
  checknow:
    description: Manually run a SwimCheck on a player.
    permission: fishon.checknow
    usage: /checknow §7[§eTargetPlayer §7or §e*§7]